kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: node-full-stack-git
  annotations:
  labels:
    app: node-full-stack-git
    app.kubernetes.io/component: node-full-stack-git
    app.kubernetes.io/instance: node-full-stack-git
    app.kubernetes.io/name: node-full-stack-git
    app.kubernetes.io/part-of: node-full-stack-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'node-full-stack-git:latest'
  resources: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:16-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/msatyan/NodeFullStack.git'
    contextDir: /
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
