kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/msatyan/NodeFullStack.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: node-full-stack-git
  labels:
    app: node-full-stack-git
    app.kubernetes.io/component: node-full-stack-git
    app.kubernetes.io/instance: node-full-stack-git
    app.kubernetes.io/name: node-full-stack-git
    app.kubernetes.io/part-of: node-full-stack-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  lookupPolicy:
    local: false
